### ISSUE TITLE
Process completed with exit code 134.

### ISSUE THREAD

**Issue by smalllqiang** [FirmianaMarsili/picacomic-Punch#16]
已經按文檔鍵入了賬號和密碼 但是一直提示

1. Run dotnet run -- ${accounts}
2.   dotnet run -- ${accounts}
3.   shell: /usr/bin/bash -e {0}
4.   env:
5.     DOTNET_ROOT: /home/runner/.dotnet
6.     accounts: 
7. Unhandled exception. System.Exception: 请查看文档设置账号密码
8.    at picacomic.Program.Main(String[] args) in /home/runner/work/picacomic-Punch/picacomic-Punch/Program.cs:line 21
9.    at picacomic.Program.<Main>(String[] args)
10. Error: Process completed with exit code 134.

鑒於這個庫最新更新是三年以前 是否因為github功能有改動?

**Comment by FirmianaMarsili** [comment]
功能依旧有效，看了下代码应该是Accounts设置错误，如果是单个账号应该是:
`账号`,`密码`
如果是多个账号应该是:
`账号`,`密码`|`账号1`,`密码1`
所有分割符号都是英文，检查一下是否都是英文符号

**Comment by smalllqiang** [comment]
問題解決
原來是因為添加Secrets時 Name不是ACCOUNTS
