### ISSUE TITLE
workflow在build这一步出错，之前能运行，今天卡

### ISSUE THREAD

**Issue by fluteink** [FirmianaMarsili/picacomic-Punch#18]
![sp20241220_110455_958](https://github.com/user-attachments/assets/2cce6f20-9b00-44dd-82c4-33f5121a0ce3)

**Comment by FirmianaMarsili** [comment]
应该是服务器偶尔抽风，可以晚点手动运行再试试

**Comment by amwangfan** [comment]
> ![sp20241220_110455_958](https://private-user-images.githubusercontent.com/41096447/397601105-2cce6f20-9b00-44dd-82c4-33f5121a0ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDc5NTAsIm5iZiI6MTczNTIwNzY1MCwicGF0aCI6Ii80MTA5NjQ0Ny8zOTc2MDExMDUtMmNjZTZmMjAtOWIwMC00NGRkLTgyYzQtMzNmNTEyMWEwY2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEwMDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYjMzODdhYWMyNTRiMjZkNDljZWFlODMzOTA2MmZmMzMyZjJkYzJkZTYzNGNmMDIzZWQ5ZDg3ZDFjMmYxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.byVn8vzc8T3TJ3tJXGFzy19sNYag8L_1UgNVt2Lu5AU)

原来的确实不行了，你k可以把picacomic-Punch.csproj第五行net5.0改成net6.0，就好了。

**Comment by fluteink** [comment]
> 还有.github/workflows/picacgPunch.yml下面的 dotnet-version: '5.0.x'改成6.0x

是的，我也刚发现，改一个不起作用，我自己也改了yml文件以后就能正常运行了，感谢
